export default function IncludedSection() {
  return (
    <section className={"section light included-section"}>
      <div className={"narrow center reveal mascot-anchor container"}>
        <img src={"/images/sticker-point.png"} alt={""} aria-hidden={"true"} className={"mascot-accent mascot-included"} />
        <div className={"section-label"}>
          What You Get
        </div>
        <h2>
          
                    Here's Everything Included With
          <br />
          <span className={"gradient-text"}>
            Social Ads Freak
          </span>
        </h2>
        <p className={"subheadline"}>
          
                    Unleash the full potential of AI-powered video ads
                
        </p>
      </div>
      <div className={"container"}>
        <div className={"included-stack"}>
          {/* Row 1: image left, text right */}
          <div className={"included-row reveal"}>
            <div className={"included-img"}>
              <video data-src={"videos/included-ugc.mp4"} poster={"/images/included-ugc-poster.jpg"} width={"1080"} height={"480"} muted loop playsInline preload={"none"} aria-label={"Four AI-generated UGC ads in talking-head, product-demo, and stunt formats"}></video>
            </div>
            <div className={"included-text"}>
              <h3>
                Freakishly Real UGC Ads
              </h3>
              <p>
                
                                Clone proven scroll-stopping ad formats —
                                talking head, product demos, testimonials,
                                unboxings — all generated by AI in minutes.
                            
              </p>
            </div>
          </div>
          {/* Row 2: text left, image right */}
          <div className={"included-row reverse reveal"}>
            <div className={"included-img"}>
              <img src={"/images/included-avatars.jpg"} alt={"Eight of the 100+ hyper-realistic AI avatars"} loading={"lazy"} />
            </div>
            <div className={"included-text"}>
              <h3>
                100+ AI Avatars
              </h3>
              <p>
                
                                Don't want your face on camera? Pick from over
                                100 hyper-realistic AI avatars across diverse
                                ages, genders, and ethnicities.
                            
              </p>
            </div>
          </div>
          {/* Row 3: image left, text right */}
          <div className={"included-row reveal"}>
            <div className={"included-img"}>
              <img src={"/images/included-languages.jpg"} alt={"The in-app language picker with 30+ languages"} loading={"lazy"} />
            </div>
            <div className={"included-text"}>
              <h3>
                30+ Languages
              </h3>
              <p>
                
                                Go global instantly. Generate ads in English,
                                Spanish, Japanese, Arabic, Hindi, and 25+ more
                                languages with native-sounding voices.
                            
              </p>
            </div>
          </div>
          {/* Row 4: text left, image right */}
          <div className={"included-row reverse reveal"}>
            <div className={"included-img"}>
              <img src={"/images/included-voice.jpg"} alt={"Clone Your Voice \u2014 upload or record a short sample"} loading={"lazy"} />
            </div>
            <div className={"included-text"}>
              <h3>
                Voice Cloning
              </h3>
              <p>
                
                                Upload a short voice sample and Social Ads Freak
                                clones your voice perfectly. Your avatar speaks
                                in your voice — in any language.
                            
              </p>
            </div>
          </div>
          {/* Row 5: image left, text right */}
          <div className={"included-row reveal"}>
            <div className={"included-img"}>
              <img src={"/images/included-captions.jpg"} alt={"The same AI ad shown with four caption looks: Freak Pop, Karaoke, Boxed and One Word"} loading={"lazy"} />
            </div>
            <div className={"included-text"}>
              <h3>
                Auto-Captions
              </h3>
              <p>
                
                                Word-by-word captions timed to the voice, in six
                                looks, kept clear of the platform buttons and
                                baked into your download. No caption app needed.
                            
              </p>
            </div>
          </div>
          {/* Row 6: text left, image right */}
          <div className={"included-row reverse reveal"}>
            <div className={"included-img"}>
              <img src={"/images/included-templates.jpg"} alt={"Battle-tested ad template formats"} loading={"lazy"} />
            </div>
            <div className={"included-text"}>
              <h3>
                Proven Ad Templates
              </h3>
              <p>
                
                                Start from battle-tested formats: hook + problem
                                + solution, demo walkthroughs, before/after
                                reveals, and testimonial scripts.
                            
              </p>
            </div>
          </div>
          {/* Row 7: image left, text right */}
          <div className={"included-row reveal"}>
            <div className={"included-img"}>
              <img src={"/images/included-export.jpg"} alt={"Export your finished movie in one click"} loading={"lazy"} />
            </div>
            <div className={"included-text"}>
              <h3>
                Export Anywhere
              </h3>
              <p>
                
                                Download your finished ads in HD and deploy
                                straight to Facebook, Instagram, TikTok, YouTube
                                — any platform, any format.
                            
              </p>
            </div>
          </div>
          {/* Row 8: text left, image right */}
          <div className={"included-row reverse reveal"}>
            <div className={"included-img"}>
              <video data-src={"videos/included-trendradar.mp4"} poster={"/images/included-trendradar-poster.jpg"} width={"1080"} height={"702"} muted loop playsInline preload={"none"} aria-label={"Trend Radar \u2014 live niche scan turned into three ready-to-generate ad concepts"}></video>
            </div>
            <div className={"included-text"}>
              <h3>
                Trend Radar
              </h3>
              <p>
                
                                Stop guessing what to post. Trend Radar
                                researches what's actually going viral in your
                                niche on TikTok, Reels, and Shorts — then hands
                                you 3 ready-to-generate ad concepts, each one
                                click from a finished video.
                            
              </p>
            </div>
          </div>
          {/* Row 9: image left, text right */}
          <div className={"included-row reveal"}>
            <div className={"included-img"}>
              <video data-src={"videos/included-prostudio.mp4"} poster={"/images/included-prostudio-poster.jpg"} width={"1080"} height={"634"} muted loop playsInline preload={"none"} aria-label={"Pro Studio \u2014 full timeline editor with preview, captions, and audio tracks"}></video>
            </div>
            <div className={"included-text"}>
              <h3>
                Pro Studio — A Second Product, Free
              </h3>
              <p>
                
                                Quick ads are half the story. Pro Studio builds
                                full multi-scene videos — AI writes the script,
                                generates every scene with multi-shot cuts,
                                voiceover, and music, and hands you a timeline
                                editor to polish it. Up to 20 scenes per story.
                            
              </p>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}
