import { SectionTitle } from '../components/Shared.jsx';

const FEATURES = [
  {
    title: 'Freakishly Real UGC Ads',
    text: 'Clone proven scroll-stopping ad formats — talking head, product demos, testimonials, unboxings — all generated by AI in minutes.',
    video: '/videos/included-ugc.mp4',
    poster: '/images/included-ugc-poster.jpg',
  },
  {
    title: '100+ AI Avatars',
    text: "Don't want your face on camera? Pick from over 100 hyper-realistic AI avatars across diverse ages, genders, and ethnicities.",
    img: '/images/included-avatars.jpg',
  },
  {
    title: '30+ Languages',
    text: 'Go global instantly. Generate ads in English, Spanish, Japanese, Arabic, Hindi, and 25+ more languages with native-sounding voices.',
    img: '/images/included-languages.jpg',
  },
  {
    title: 'Voice Cloning',
    text: 'Upload a short voice sample and Social Ads Freak clones your voice perfectly. Your avatar speaks in your voice — in any language.',
    img: '/images/included-voice.jpg',
  },
  {
    title: 'Auto-Captions',
    text: 'Word-by-word captions timed to the voice, in six looks, kept clear of the platform buttons and baked into your download. No caption app needed.',
    img: '/images/included-captions.jpg',
  },
  {
    title: 'Proven Ad Templates',
    text: 'Start from battle-tested formats: hook + problem + solution, demo walkthroughs, before/after reveals, and testimonial scripts.',
    img: '/images/included-templates.jpg',
  },
  {
    title: 'Export Anywhere',
    text: 'Download your finished ads in HD and deploy straight to Facebook, Instagram, TikTok, YouTube — any platform, any format.',
    img: '/images/included-export.jpg',
  },
  {
    title: 'Trend Radar',
    text: "Stop guessing what to post. Trend Radar researches what's actually going viral in your niche on TikTok, Reels, and Shorts — then hands you 3 ready-to-generate ad concepts, each one click from a finished video.",
    video: '/videos/included-trendradar.mp4',
    poster: '/images/included-trendradar-poster.jpg',
  },
  {
    title: 'Pro Studio — A Second Product, Free',
    text: 'Quick ads are half the story. Pro Studio builds full multi-scene videos — AI writes the script, generates every scene with multi-shot cuts, voiceover, and music, and hands you a timeline editor to polish it. Up to 20 scenes per story.',
    video: '/videos/included-prostudio.mp4',
    poster: '/images/included-prostudio-poster.jpg',
  },
];

export default function EverythingIncluded() {
  return (
    <section className="included">
      <div className="container">
        <SectionTitle
          kicker="What You Get — Worth $766, Yours For $47"
          title="Here's Everything Included With"
          highlight="Social Ads Freak"
          sub="Nine weapons. One login. Each of these alone would cost more than today's entire price."
        />
        <div className="included-list">
          {FEATURES.map((f, i) => (
            <div className={`included-row${i % 2 ? ' reverse' : ''}`} key={f.title}>
              <div className="included-copy">
                <span className="included-index">{String(i + 1).padStart(2, '0')}</span>
                <h3>{f.title}</h3>
                <p>{f.text}</p>
              </div>
              <div className="included-media-wrap">
                {f.video ? (
                  <video
                    className="included-media"
                    src={f.video}
                    poster={f.poster}
                    muted
                    autoPlay
                    loop
                    playsInline
                    preload="metadata"
                  ></video>
                ) : (
                  <img className="included-media" src={f.img} alt={f.title} loading="lazy" />
                )}
              </div>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
}
