import { Section, Title, Label } from '../ui.jsx';

const FEATURES = [
  { title: 'Freakishly Real UGC Ads', lead: 'Clone proven scroll-stopping formats — talking head, product demos, testimonials, unboxings.', text: 'All generated by AI in minutes, with the hook, pacing and CTA of ads that already won.', video: '/videos/included-ugc.mp4', poster: '/images/included-ugc-poster.jpg' },
  { title: '100+ AI Avatars', lead: "Don't want your face on camera? Pick from over 100 hyper-realistic AI avatars.", text: 'Diverse ages, genders and ethnicities — or upload one photo and become your own avatar.', img: '/images/included-avatars.jpg' },
  { title: '30+ Languages', lead: 'Go global instantly with native-sounding voices.', text: 'English, Spanish, Japanese, Arabic, Hindi and 25+ more — the same winning ad, localized in a click.', img: '/images/included-languages.jpg' },
  { title: 'Voice Cloning', lead: 'Upload a short voice sample and Social Ads Freak clones your voice perfectly.', text: 'Your avatar speaks in your voice — in any language.', img: '/images/included-voice.jpg' },
  { title: 'Auto-Captions', lead: 'Word-by-word captions timed to the voice, in six looks.', text: 'Kept clear of the platform buttons and baked into your download. No caption app needed.', img: '/images/included-captions.jpg' },
  { title: 'Proven Ad Templates', lead: 'Start from 274 battle-tested formats.', text: 'Hook + problem + solution, demo walkthroughs, before/after reveals and testimonial scripts.', img: '/images/included-templates.jpg' },
  { title: 'Export Anywhere', lead: 'Download your finished ads in HD.', text: 'Deploy straight to Facebook, Instagram, TikTok, YouTube — any platform, any format.', img: '/images/included-export.jpg' },
  { title: 'Trend Radar', lead: "Stop guessing what to post. Trend Radar researches what's actually going viral in your niche.", text: 'Then hands you 3 ready-to-generate ad concepts, each one click from a finished video.', video: '/videos/included-trendradar.mp4', poster: '/images/included-trendradar-poster.jpg' },
  { title: 'Pro Studio — A Second Product, Free', lead: 'Quick ads are half the story. Pro Studio builds full multi-scene videos.', text: 'AI writes the script, generates every scene with voiceover and music, and hands you a timeline editor. Up to 20 scenes per story.', video: '/videos/included-prostudio.mp4', poster: '/images/included-prostudio-poster.jpg' },
];

export default function Included() {
  return (
    <Section className="included">
      <Label>What You Get</Label>
      <Title>Here's Everything Included With <b className="grad">Social Ads Freak</b></Title>
      <p className="lead">Unleash The Full Potential of Artificial Intelligence</p>
      {FEATURES.map((f, i) => (
        <div className={`feature${i % 2 ? ' reverse' : ''}`} key={f.title}>
          <div className="feature-copy">
            <h3 className="grad">{f.title}</h3>
            <p className="feature-lead">{f.lead}</p>
            <p>{f.text}</p>
          </div>
          {f.video
            ? <video src={f.video} poster={f.poster} muted autoPlay loop playsInline preload="metadata" />
            : <img src={f.img} alt={f.title} loading="lazy" />}
        </div>
      ))}
    </Section>
  );
}
